import { v4 as uuid } from 'uuid';
import { ShoppingBag as ShoppingBagIcon } from '../icons/shopping-bag';

export const products = [
  {
    id: uuid(),
    createdAt: '27/03/2019',
    description: 'Quedan 8 sectores disponibles en el rango fecha/hora seleccionado',
    media: '/static/images/products/soccer.png',
    title: 'Cancha 1',
    totalDownloads: '594',
    href:'/product-selected-item',
    icon:(<ShoppingBagIcon fontSize="small" />),
  },
  {
    id: uuid(),
    createdAt: '31/03/2019',
    description: 'Quedan 10 sectores disponibles en el rango fecha/hora seleccionado',
    media: '/static/images/products/soccer2.png',
    title: 'Cancha 2',
    totalDownloads: '625',
    href:'/product-selected-item',
    icon:(<ShoppingBagIcon fontSize="small" />),
  },
  {
    id: uuid(),
    createdAt: '03/04/2019',
    description: 'Quedan 16 sectores disponibles en el rango fecha/hora seleccionado',
    media: '/static/images/products/soccer3.png',
    title: 'Cancha 3',
    totalDownloads: '857',
    href:'/product-selected-item',
    icon:(<ShoppingBagIcon fontSize="small" />),
  },
  {
    id: uuid(),
    createdAt: '04/04/2019',
    description: 'Quedan 8 sectores disponibles en el rango fecha/hora seleccionado',
    media: '/static/images/products/soccer3.png',
    title: 'Cancha 4',
    totalDownloads: '406',
    href:'/product-selected-item',
    icon:(<ShoppingBagIcon fontSize="small" />),
  },
  {
    id: uuid(),
    createdAt: '04/04/2019',
    description: 'Quedan 8 sectores disponibles en el rango fecha/hora seleccionado',
    media: '/static/images/products/soccer.png',
    title: 'Cancha 5',
    totalDownloads: '835',
    href:'/product-selected-item',
    icon:(<ShoppingBagIcon fontSize="small" />),
  },
  {
    id: uuid(),
    createdAt: '04/04/2019',
    description: 'Quedan 8 sectores disponibles en el rango fecha/hora seleccionado',
    media: '/static/images/products/soccer2.png',
    title: 'Cancha 6',
    totalDownloads: '835',
    href:'/product-selected-item',
    icon:(<ShoppingBagIcon fontSize="small" />),
  }
];
